sudo: required

language: generic

branches:
  only:
  - master

services:
  - docker

env:
  - PHP_VERSION=7.0 DEBIAN_RELEASE=stretch
  - PHP_VERSION=7.1 DEBIAN_RELEASE=stretch
  - PHP_VERSION=7.2 DEBIAN_RELEASE=stretch
  - PHP_VERSION=7.0 DEBIAN_RELEASE=jessie
  - PHP_VERSION=7.1 DEBIAN_RELEASE=jessie
  - PHP_VERSION=7.2 DEBIAN_RELEASE=jessie

script:
  - bin/build.sh
  - bin/push.sh
