#!/bin/bash

PHP_VERSION=$CACHE_TAG
if [ -z "$CACHE_TAG" ]; then
    PHP_VERSION=7.1
fi

BASE_IMAGE=php:${PHP_VERSION}-apache

echo "=> Building start with args"
echo "PHP_VERSION=${PHP_VERSION}"
echo "BASE_IMAGE=${BASE_IMAGE}"


docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t $IMAGE_NAME .